# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_list',
            fields=[
                ('cod_item', models.AutoField(primary_key=True, serialize=False)),
                ('nm_item', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descricao')),
                ('sn_feito', models.BooleanField(default=False, verbose_name='Feito')),
            ],
            options={
                'verbose_name_plural': 'To-Do List',
                'verbose_name': 'To-Do List',
            },
        ),
    ]
